# Run on ubuntu
dist: bionic

# Don't use
sudo: false

# Define the language and versions that infoset is written in
language: node_js
node:
  - 10

# Run tests only against the master branch
# branches:
#   only:
#     - master

# Install node modules and packages before testing
before_install:
  - npm install

# Run the unittest scripts
script: npm test
