# Run on ubuntu
dist: bionic

# Don't use
sudo: false

# Define the language and versions that infoset is written in
language: python
python:
  - 3.6

# Run tests only against the master branch
# branches:
#   only:
#     - master

# Setup services
services:
  - mysql

# Setup global environmental variables
env:
    - PYTHONPATH=./ PATTOO_CONFIGDIR=$HOME/.pattoo-web-unittests/config

# Install PIP packages and create a temporary config file before installing
before_install:
    - pip install -r pip_requirements.txt
    - tests/bin/unittest_setup.py

# Run the unittest scripts
script: tests/bin/do_all_tests.py
